title: "Yuanyuan Zhang"
description: "Graduate Student at Boston University"
url: "https://yourusername.github.io"
baseurl: ""

remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-remote-theme

author:
  name: "Yuanyuan Zhang"
  avatar: "/assets/images/your-photo.jpg"
  bio: "Graduate student specializing in syntax and semantics."

