
title: "My Personal Website"
description: "A site showcasing my academic work and interests."
baseurl: "" # 如果是根目录，留空
url: "https://your-username.github.io"

theme: jekyll-theme-minimal # 或其他主题

# 插件（如需）
plugins:
  - jekyll-paginate
  - jekyll-seo-tag

