title: "Yuanyuan's Personal Website"
description: "Welcome to my personal website!"
baseurl: "" # 根目录为空
url: "https://yourusername.github.io"

# 主题相关配置（根据主题文档更新）
theme_settings:
  color_scheme: "dark"
  show_avatar: true
